Repository woowa-techcamp-2022/android-banchan-06, pull requests merged in 2022-08, with the labels that each got.

#6 [Feature] Presentation 모듈에 Retrofit Module 작성
  build.gradle
  presentation/build.gradle
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/woowahan/banchan/application/BanchanOrderApplication.kt
  presentation/src/main/java/com/woowahan/banchan/di/AppModule.kt
  presentation/src/main/java/com/woowahan/banchan/di/RetrofitModule.kt
Labels: Feature 📎, 웅재 🦊

#3 [Feature] 반찬 주문앱 Api 들의 Entity
  data/build.gradle
  data/src/main/java/com/woowahan/data/entity/BanchanDetailEntity.kt
  data/src/main/java/com/woowahan/data/entity/BanchanEntity.kt
  data/src/main/java/com/woowahan/data/entity/ContestBanchanEntity.kt
  data/src/main/java/com/woowahan/data/entity/MainDishBanchanEntity.kt
  data/src/main/java/com/woowahan/data/entity/SideDishBanchanEntity.kt
  data/src/main/java/com/woowahan/data/entity/SoupDishBanchanEntity.kt
Labels: Feature 📎, 웅재 🦊

#9 [Feature] Presentation 모듈에 Base Activity, Base Fragment 생성
  presentation/build.gradle
  presentation/src/main/java/com/woowahan/banchan/LifeCycleLogObserver.kt
  presentation/src/main/java/com/woowahan/banchan/application/BanchanOrderApplication.kt
  presentation/src/main/java/com/woowahan/banchan/ui/base/BaseActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/base/BaseFragment.kt
  presentation/src/main/java/com/woowahan/banchan/util/AppCompatExtension.kt
  presentation/src/main/java/com/woowahan/banchan/util/FragmentExtension.kt
Labels: Feature 📎, 웅재 🦊

#10 [Feature] Data 모듈에 Api Service, DataSource 정의
  data/build.gradle
  data/src/main/java/com/woowahan/data/apiservice/BanchanDetailApiService.kt
  data/src/main/java/com/woowahan/data/apiservice/BestBanchanApiService.kt
  data/src/main/java/com/woowahan/data/apiservice/MainDishBanchanApiService.kt
  data/src/main/java/com/woowahan/data/apiservice/SideDishBanchanApiService.kt
  data/src/main/java/com/woowahan/data/apiservice/SoupDishBanchanApiService.kt
  data/src/main/java/com/woowahan/data/datasource/BanchanDetailDataSource.kt
  data/src/main/java/com/woowahan/data/datasource/BanchanDetailDataSourceImpl.kt
  data/src/main/java/com/woowahan/data/datasource/BanchansDataSource.kt
  data/src/main/java/com/woowahan/data/datasource/BanchansRetrofitDataSourceImpl.kt
  data/src/main/java/com/woowahan/data/entity/BestBanchanEntity.kt
  data/src/main/java/com/woowahan/data/util/RetrofitResponseConvertUtil.kt
  presentation/src/main/java/com/woowahan/banchan/di/ApiServiceModule.kt
  presentation/src/main/java/com/woowahan/banchan/di/AppModule.kt
Labels: Feature 📎, 웅재 🦊

#14 [Design] 공통 컴포넌트 개발
  presentation/src/main/res/drawable/bg_add_cart_checked.xml
  presentation/src/main/res/drawable/bg_grid_checked.xml
  presentation/src/main/res/drawable/bg_linear_checked.xml
  presentation/src/main/res/drawable/ic_arrow_left.xml
  presentation/src/main/res/drawable/ic_arrow_right.xml
  presentation/src/main/res/drawable/ic_cart.xml
  presentation/src/main/res/drawable/ic_check_black.xml
  presentation/src/main/res/drawable/ic_check_white.xml
  presentation/src/main/res/drawable/ic_checkbox_checked.xml
  presentation/src/main/res/drawable/ic_checkbox_empty.xml
  presentation/src/main/res/drawable/ic_close.xml
  presentation/src/main/res/drawable/ic_down.xml
  presentation/src/main/res/drawable/ic_grid_black.xml
  presentation/src/main/res/drawable/ic_grid_white.xml
  presentation/src/main/res/drawable/ic_linear_black.xml
  presentation/src/main/res/drawable/ic_linear_white.xml
  presentation/src/main/res/drawable/ic_minus.xml
  presentation/src/main/res/drawable/ic_plus.xml
  presentation/src/main/res/drawable/ic_reload.xml
  presentation/src/main/res/drawable/ic_user.xml
  presentation/src/main/res/drawable/rectangle_white_top_radius_15.xml
  presentation/src/main/res/drawable/sel_btn_add_cart.xml
  presentation/src/main/res/drawable/sel_btn_grid.xml
  presentation/src/main/res/drawable/sel_btn_linear.xml
  presentation/src/main/res/drawable/sel_main_btn.xml
  presentation/src/main/res/layout/dialog_cart_add.xml
  presentation/src/main/res/layout/item_menu_horizontal.xml
  presentation/src/main/res/layout/item_menu_small.xml
  presentation/src/main/res/layout/item_menu_time_stamp.xml
  presentation/src/main/res/layout/item_menu_vertical.xml
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/dimen.xml
  presentation/src/main/res/values/strings.xml
Labels: Design 🖍, 영무 🍗

#12 [Feature] Domain 모듈에 banchan data model class, Repository UseCase 추가
  domain/src/main/java/com/woowahan/domain/MyClass.kt
  domain/src/main/java/com/woowahan/domain/model/BanchanModel.kt
  domain/src/main/java/com/woowahan/domain/model/BestBanchanModel.kt
  domain/src/main/java/com/woowahan/domain/repository/BanchanRepository.kt
  domain/src/main/java/com/woowahan/domain/usecase/FetchBestBanchanUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/FetchMainDishBanchanUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/FetchSideDishBanchanUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/FetchSoupDishBanchanUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/FilterBanchanUseCase.kt
Labels: Feature 📎, 웅재 🦊

#16 [Feature] Main화면 Tab 기초 구조 생성
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/woowahan/banchan/MainActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/bestbanchan/BestBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/main/MainActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/main/MainTabPagerAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/maindishbanchan/MainDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/sidedishbanchan/SideDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/soupdishbanchan/SoupDishBanchanFragment.kt
  presentation/src/main/res/drawable/bg_main_tab_layout.xml
  presentation/src/main/res/layout/activity_main.xml
  presentation/src/main/res/layout/fragment_best_banchan.xml
  presentation/src/main/res/layout/fragment_main_dish_banchan.xml
  presentation/src/main/res/layout/fragment_side_dish_banchan.xml
  presentation/src/main/res/layout/fragment_soup_dish_banchan.xml
  presentation/src/main/res/values-night/themes.xml
  presentation/src/main/res/values/dimen.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/themes.xml
Labels: Feature 📎, 웅재 🦊, 영무 🍗, Pair 🤝

#18 [Feature] BanchanRepositoryImpl 구현
  data/build.gradle
  data/src/main/java/com/woowahan/data/entity/BanchanEntity.kt
  data/src/main/java/com/woowahan/data/entity/BestBanchanEntity.kt
  data/src/main/java/com/woowahan/data/repository/BanchanRepositoryImpl.kt
  data/src/main/java/com/woowahan/data/util/RetrofitResponseConvertUtil.kt
  domain/build.gradle
  presentation/src/main/java/com/woowahan/banchan/di/AppModule.kt
  presentation/src/main/java/com/woowahan/banchan/di/DataSourceModule.kt
  presentation/src/main/java/com/woowahan/banchan/di/RepositoryModule.kt
Labels: Feature 📎, 웅재 🦊, 영무 🍗, Pair 🤝

#21 [Feature] 메인요리 구현
  domain/src/main/java/com/woowahan/domain/model/BanchanModel.kt
  domain/src/main/java/com/woowahan/domain/usecase/FilterBanchanUseCase.kt
  presentation/build.gradle
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/woowahan/banchan/BanchanModelDiffUtilCallback.kt
  presentation/src/main/java/com/woowahan/banchan/bindingadapter/ImageViewBindingAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/di/UseCaseModule.kt
  presentation/src/main/java/com/woowahan/banchan/ui/main/MainActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/maindishbanchan/MainDishBanchanAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/maindishbanchan/MainDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/MainDishBanchanViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/util/FilterBanchanListUtil.kt
  presentation/src/main/java/com/woowahan/banchan/util/IntExtension.kt
  presentation/src/main/res/drawable/bg_best_label.xml
  presentation/src/main/res/drawable/bg_error.xml
  presentation/src/main/res/drawable/bg_image_placeholder.xml
  presentation/src/main/res/drawable/bg_spinner.xml
  presentation/src/main/res/drawable/ic_error.xml
  presentation/src/main/res/drawable/ic_grid_black.xml
  presentation/src/main/res/drawable/ic_grid_gray.xml
  presentation/src/main/res/drawable/ic_linear_gray.xml
  presentation/src/main/res/drawable/sel_btn_grid.xml
  presentation/src/main/res/drawable/sel_btn_linear.xml
  presentation/src/main/res/layout/fragment_main_dish_banchan.xml
  presentation/src/main/res/layout/item_bachan_list_banner.xml
  presentation/src/main/res/layout/item_filter_spinner.xml
  presentation/src/main/res/layout/item_menu_horizontal.xml
  presentation/src/main/res/layout/item_menu_vertical.xml
  presentation/src/main/res/layout/item_view_mode_toggle_header.xml
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/dimen.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/themes.xml
Labels: Feature 📎, 웅재 🦊, 영무 🍗, Pair 🤝

#28 [Feature] 장바구니 기능 Data, Domain 모듈 작업
  data/src/main/java/com/woowahan/data/datasource/CartDataSource.kt
  data/src/main/java/com/woowahan/data/datasource/CartDataSourceImpl.kt
  data/src/main/java/com/woowahan/data/repository/CartRepositoryImpl.kt
  domain/src/main/java/com/woowahan/domain/repository/CartRepository.kt
  domain/src/main/java/com/woowahan/domain/usecase/FetchCartItemsUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/InsertCartItemUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/RemoveCartItemUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/RemoveCartItemsUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/UpdateCartItemUseCase.kt
  presentation/src/main/java/com/woowahan/banchan/di/DataSourceModule.kt
  presentation/src/main/java/com/woowahan/banchan/di/RepositoryModule.kt
  presentation/src/main/java/com/woowahan/banchan/di/UseCaseModule.kt
Labels: Feature 📎, 웅재 🦊

#29 [Refactor] ViewModel의 LiveData를 Flow 사용으로 변경
  presentation/src/main/java/com/woowahan/banchan/ui/maindishbanchan/MainDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/MainDishBanchanViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/util/LifeCyclerOwnerExtension.kt
Labels: Refactor ⚒, 웅재 🦊, 영무 🍗, Pair 🤝

#30 [Refactor] ViewModel에 UIEvent sealed class를 생성하여 Event들을 통합 관리
  presentation/src/main/java/com/woowahan/banchan/ui/maindishbanchan/MainDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/MainDishBanchanViewModel.kt
  presentation/src/main/res/layout/fragment_main_dish_banchan.xml
Labels: Refactor ⚒, 웅재 🦊, 영무 🍗, Pair 🤝

#32 [Rename] MainActivity #31
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/woowahan/banchan/ui/root/RootActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/root/RootTabPagerAdapter.kt
  presentation/src/main/res/layout/activity_main.xml
Labels: 영무 🍗, Rename 🪄

#38 [Feature] 장바구니 담기 Bottom Sheet Kotlin Class 작성, 장바구니 추가, 제거 기능 연동
  data/src/main/java/com/woowahan/data/datasource/CartDataSource.kt
  data/src/main/java/com/woowahan/data/datasource/CartDataSourceImpl.kt
  data/src/main/java/com/woowahan/data/repository/CartRepositoryImpl.kt
  domain/src/main/java/com/woowahan/domain/model/BanchanModel.kt
  domain/src/main/java/com/woowahan/domain/repository/CartRepository.kt
  domain/src/main/java/com/woowahan/domain/usecase/FetchBestBanchanUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/FetchCartItemsUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/FetchMainDishBanchanUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/FetchSideDishBanchanUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/FetchSoupDishBanchanUseCase.kt
  presentation/src/main/java/com/woowahan/banchan/BanchanModelDiffUtilCallback.kt
  presentation/src/main/java/com/woowahan/banchan/di/UseCaseModule.kt
  presentation/src/main/java/com/woowahan/banchan/ui/dialog/CartItemInsertBottomSheet.kt
  presentation/src/main/java/com/woowahan/banchan/ui/maindishbanchan/MainDishBanchanAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/maindishbanchan/MainDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/MainDishBanchanViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/util/FilterBanchanListUtil.kt
  presentation/src/main/java/com/woowahan/banchan/util/List<BanchanModel>Extension.kt
  presentation/src/main/java/com/woowahan/banchan/util/LongExtension.kt
  presentation/src/main/res/drawable/sel_main_btn.xml
  presentation/src/main/res/layout/dialog_cart_add.xml
  presentation/src/main/res/layout/item_menu_horizontal.xml
  presentation/src/main/res/layout/item_menu_vertical.xml
  presentation/src/main/res/values/colors.xml
Labels: Feature 📎, 웅재 🦊

#36 [Fix] Price 정렬 방법 수정
  presentation/src/main/java/com/woowahan/banchan/util/List<BanchanModel>Extension.kt
Labels: Fix 🔎, 영무 🍗

#33 [Feature] 국물 요리 구현 #23
  presentation/src/main/java/com/woowahan/banchan/ui/soupdishbanchan/SoupDishBanchanAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/soupdishbanchan/SoupDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SoupDishBanchanViewModel.kt
  presentation/src/main/res/layout/fragment_soup_dish_banchan.xml
  presentation/src/main/res/layout/item_count_header.xml
Labels: Feature 📎, 영무 🍗

#34 [Feature] 밑반찬 구현 #27
  presentation/src/main/java/com/woowahan/banchan/ui/sidedishbanchan/SideDishBanchanAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/sidedishbanchan/SideDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SideDishBanchanViewModel.kt
  presentation/src/main/res/layout/fragment_side_dish_banchan.xml
Labels: Feature 📎, 영무 🍗

#48 [Design] 장바구니 선택된 상태일 때 아이콘 변경
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/DefaultBanchanAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/FilterSpinnerAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/ViewModeToggleBanchanAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/decoratin/GridItemDecoration.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/viewHolder/BanchanListBannerViewHolder.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/viewHolder/CountHeaderViewHolder.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/viewHolder/MenuHorizontalViewHolder.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/viewHolder/MenuVerticalViewHolder.kt
  presentation/src/main/java/com/woowahan/banchan/ui/maindishbanchan/MainDishBanchanAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/maindishbanchan/MainDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/sidedishbanchan/SideDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/soupdishbanchan/SoupDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SideDishBanchanViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SoupDishBanchanViewModel.kt
  presentation/src/main/res/drawable/bg_add_cart_checked.xml
  presentation/src/main/res/drawable/bg_cart_padding.xml
  presentation/src/main/res/layout/fragment_main_dish_banchan.xml
  presentation/src/main/res/layout/fragment_side_dish_banchan.xml
  presentation/src/main/res/layout/fragment_soup_dish_banchan.xml
  presentation/src/main/res/layout/item_count_header.xml
  presentation/src/main/res/layout/item_menu_horizontal.xml
  presentation/src/main/res/layout/item_menu_time_stamp.xml
  presentation/src/main/res/layout/item_menu_vertical.xml
  presentation/src/main/res/layout/item_view_mode_toggle_header.xml
Labels: Design 🖍, 영무 🍗

#41 [Feature] 장바구니 DataSource에서 지속적으로 관찰 가능한 Flow형태를 RootActivity에서 관찰 가능한지 검토
  data/src/main/java/com/woowahan/data/datasource/CartDataSource.kt
  data/src/main/java/com/woowahan/data/datasource/CartDataSourceImpl.kt
  data/src/main/java/com/woowahan/data/repository/CartRepositoryImpl.kt
  domain/src/main/java/com/woowahan/domain/repository/CartRepository.kt
  domain/src/main/java/com/woowahan/domain/usecase/GetCartItemsSizeFlowUseCase.kt
  presentation/src/main/java/com/woowahan/banchan/di/UseCaseModule.kt
  presentation/src/main/java/com/woowahan/banchan/ui/root/RootActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/RootViewModel.kt
Labels: Feature 📎, 웅재 🦊

#50 [Fix] 국물요리, 밑반찬 종종 바로 안 뜨는 오류
  presentation/src/main/java/com/woowahan/banchan/ui/root/RootActivity.kt
Labels: Fix 🔎, 웅재 🦊

#52 [Feature] 반찬주문앱 Dialog 제작
  presentation/src/main/java/com/woowahan/banchan/extension/AppCompatExtension.kt
  presentation/src/main/java/com/woowahan/banchan/extension/FragmentExtension.kt
  presentation/src/main/java/com/woowahan/banchan/extension/IntExtension.kt
  presentation/src/main/java/com/woowahan/banchan/extension/LifeCyclerOwnerExtension.kt
  presentation/src/main/java/com/woowahan/banchan/extension/List<BanchanModel>Extension.kt
  presentation/src/main/java/com/woowahan/banchan/extension/LongExtension.kt
  presentation/src/main/java/com/woowahan/banchan/ui/dialog/CartItemInsertBottomSheet.kt
  presentation/src/main/java/com/woowahan/banchan/ui/dialog/MainDialog.kt
  presentation/src/main/java/com/woowahan/banchan/ui/maindishbanchan/MainDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/MainDishBanchanViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/util/DialogUtil.kt
  presentation/src/main/res/drawable/bg_main_dialog.xml
  presentation/src/main/res/layout/dialog_main.xml
  presentation/src/main/res/values/dimen.xml
Labels: Feature 📎, 웅재 🦊

#56 [Fix] #55 Extension 파일들의 패키지 이동으로 인한 kotlin file들의 import 문제 수정
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/decoratin/GridItemDecoration.kt
  presentation/src/main/java/com/woowahan/banchan/ui/root/RootActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/sidedishbanchan/SideDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/soupdishbanchan/SoupDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SideDishBanchanViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SoupDishBanchanViewModel.kt
Labels: Fix 🔎, 웅재 🦊

#54 [Feature] App Bar 제작
  presentation/src/main/java/com/woowahan/banchan/ui/root/RootActivity.kt
  presentation/src/main/res/drawable/bg_badge.xml
  presentation/src/main/res/drawable/ic_mypage.xml
  presentation/src/main/res/drawable/ic_mypage_badge.xml
  presentation/src/main/res/layout/activity_main.xml
  presentation/src/main/res/layout/item_badge_cart.xml
  presentation/src/main/res/layout/item_toolbar_main.xml
  presentation/src/main/res/layout/item_toolbar_sub.xml
  presentation/src/main/res/menu/menu_main_action_bar.xml
  presentation/src/main/res/values-night/themes.xml
  presentation/src/main/res/values/themes.xml
Labels: Feature 📎, 웅재 🦊

#57 [Design] 장바구니 Bottom Sheet Fragment Radius 처리
  presentation/src/main/java/com/woowahan/banchan/ui/dialog/CartItemInsertBottomSheet.kt
  presentation/src/main/java/com/woowahan/banchan/ui/root/RootActivity.kt
  presentation/src/main/res/values-night/themes.xml
  presentation/src/main/res/values/styles.xml
  presentation/src/main/res/values/themes.xml
Labels: Design 🖍, 웅재 🦊

#59 [Design] 클릭 효과 미부여된 곳에 머터리얼 컴포넌트 기본 ripple 효과랑 유사하게 ripple 효과 부여
  presentation/src/main/res/drawable/sel_main_btn.xml
  presentation/src/main/res/layout/dialog_cart_add.xml
  presentation/src/main/res/layout/item_menu_horizontal.xml
  presentation/src/main/res/layout/item_menu_vertical.xml
  presentation/src/main/res/layout/item_view_mode_toggle_header.xml
Labels: Design 🖍, 웅재 🦊

#61 [Fix] Grid item 여백 오류
  presentation/src/main/java/com/woowahan/banchan/ui/maindishbanchan/MainDishBanchanFragment.kt
  presentation/src/main/res/layout/item_menu_horizontal.xml
Labels: Design 🖍, Fix 🔎, 웅재 🦊

#69 [Feature] DataBase 설계 토대로 Room 연동
  data/build.gradle
  data/src/main/java/com/woowahan/data/apiservice/BanchanDetailApiService.kt
  data/src/main/java/com/woowahan/data/dao/CartDao.kt
  data/src/main/java/com/woowahan/data/database/BanchanRoomDatabase.kt
  data/src/main/java/com/woowahan/data/datasource/BanchanDetailRetrofitDataSourceImpl.kt
  data/src/main/java/com/woowahan/data/datasource/CartDataSource.kt
  data/src/main/java/com/woowahan/data/datasource/CartDataSourceImpl.kt
  data/src/main/java/com/woowahan/data/entity/BanchanDetailEntity.kt
  data/src/main/java/com/woowahan/data/entity/dto/CartDto.kt
  data/src/main/java/com/woowahan/data/entity/dto/OrderDto.kt
  data/src/main/java/com/woowahan/data/entity/dto/RecentViewedDto.kt
  data/src/main/java/com/woowahan/data/entity/table/BanchanItemTableEntity.kt
  data/src/main/java/com/woowahan/data/entity/table/CartTableEntity.kt
  data/src/main/java/com/woowahan/data/entity/table/OrderItemTableEntity.kt
  data/src/main/java/com/woowahan/data/entity/table/OrderTableEntity.kt
  data/src/main/java/com/woowahan/data/entity/table/RecentViewedTableEntity.kt
  data/src/main/java/com/woowahan/data/repository/BanchanDetailRepositoryImpl.kt
  data/src/main/java/com/woowahan/data/repository/CartRepositoryImpl.kt
  domain/src/main/java/com/woowahan/domain/BanchanDateConverter.kt
  domain/src/main/java/com/woowahan/domain/extension/StringExtension.kt
  domain/src/main/java/com/woowahan/domain/model/BanchanDetailModel.kt
  domain/src/main/java/com/woowahan/domain/model/BanchanModel.kt
  domain/src/main/java/com/woowahan/domain/model/CartModel.kt
  domain/src/main/java/com/woowahan/domain/repository/BanchanDetailRepository.kt
  domain/src/main/java/com/woowahan/domain/repository/CartRepository.kt
  domain/src/main/java/com/woowahan/domain/usecase/FetchBestBanchanUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/FetchCartItemsKeyUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/FetchCartItemsUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/FetchMainDishBanchanUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/FetchSideDishBanchanUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/FetchSoupDishBanchanUseCase.kt
  presentation/build.gradle
  presentation/src/main/java/com/woowahan/banchan/di/AppModule.kt
  presentation/src/main/java/com/woowahan/banchan/di/DaoModule.kt
  presentation/src/main/java/com/woowahan/banchan/di/DataSourceModule.kt
  presentation/src/main/java/com/woowahan/banchan/di/RepositoryModule.kt
  presentation/src/main/java/com/woowahan/banchan/di/UseCaseModule.kt
Labels: Feature 📎, 웅재 🦊, 영무 🍗, Pair 🤝

#70 [fix] app bar 장바구니 아이콘 클릭 안되는 문제
  presentation/src/main/java/com/woowahan/banchan/ui/root/RootActivity.kt
  presentation/src/main/res/layout/item_badge_cart.xml
Labels: Fix 🔎, 웅재 🦊

#72 [Feature] 장바구니 추가, 제거시 Dialog 표시
  presentation/src/main/java/com/woowahan/banchan/ui/maindishbanchan/MainDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/sidedishbanchan/SideDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/soupdishbanchan/SoupDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/MainDishBanchanViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SideDishBanchanViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SoupDishBanchanViewModel.kt
Labels: Feature 📎, 웅재 🦊

#76 [Refactor] Banchan Repository, UseCase의 비동기처리를 Flow를 사용하여 구현 검토, 적용
  data/src/main/java/com/woowahan/data/repository/BanchanDetailRepositoryImpl.kt
  data/src/main/java/com/woowahan/data/repository/BanchanRepositoryImpl.kt
  domain/src/main/java/com/woowahan/domain/repository/BanchanDetailRepository.kt
  domain/src/main/java/com/woowahan/domain/repository/BanchanRepository.kt
  domain/src/main/java/com/woowahan/domain/usecase/FetchBestBanchanUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/FetchMainDishBanchanUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/FetchSideDishBanchanUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/FetchSoupDishBanchanUseCase.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/MainDishBanchanViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SideDishBanchanViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SoupDishBanchanViewModel.kt
Labels: Refactor ⚒, 웅재 🦊

#82 [Feature] Cart Table Entity 에 select 속성 추가
  data/src/main/java/com/woowahan/data/dao/CartDao.kt
  data/src/main/java/com/woowahan/data/datasource/CartDataSource.kt
  data/src/main/java/com/woowahan/data/datasource/CartDataSourceImpl.kt
  data/src/main/java/com/woowahan/data/entity/dto/CartDto.kt
  data/src/main/java/com/woowahan/data/entity/table/CartTableEntity.kt
  data/src/main/java/com/woowahan/data/repository/CartRepositoryImpl.kt
  domain/src/main/java/com/woowahan/domain/repository/CartRepository.kt
  domain/src/main/java/com/woowahan/domain/usecase/UpdateCartItemCountUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/UpdateCartItemSelectUseCase.kt
  presentation/src/main/java/com/woowahan/banchan/di/UseCaseModule.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/DefaultCartAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/CartViewModel.kt
Labels: Feature 📎, 웅재 🦊, 영무 🍗, Pair 🤝

#77 [fix] View Mode Toggle, Filter 버그 수정
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/ViewModeToggleBanchanAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/maindishbanchan/MainDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/MainDishBanchanViewModel.kt
Labels: Fix 🔎, 웅재 🦊

#83 [Feature] 기획전 화면 구현
  domain/src/main/java/com/woowahan/domain/usecase/FetchBestBanchanUseCase.kt
  presentation/src/main/java/com/woowahan/banchan/extension/List<BestBanchan>Extension.kt
  presentation/src/main/java/com/woowahan/banchan/extension/RecyclerViewExtension.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/BestBanchanAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/DefaultBanchanAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/HorizontalBanchanListAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/viewHolder/BanchanListBannerViewHolder.kt
  presentation/src/main/java/com/woowahan/banchan/ui/bestbanchan/BestBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/sidedishbanchan/SideDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/soupdishbanchan/SoupDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/BestBanchanViewModel.kt
  presentation/src/main/res/layout/fragment_best_banchan.xml
  presentation/src/main/res/layout/item_bachan_list_banner.xml
  presentation/src/main/res/layout/item_menu_best_horizontal_child.xml
  presentation/src/main/res/layout/item_menu_horizontal_list.xml
  presentation/src/main/res/values/strings.xml
Labels: Feature 📎, 웅재 🦊

#80 [Feature] 장바구니 화면 구현
  data/src/main/java/com/woowahan/data/dao/CartDao.kt
  data/src/main/java/com/woowahan/data/datasource/CartDataSource.kt
  data/src/main/java/com/woowahan/data/datasource/CartDataSourceImpl.kt
  data/src/main/java/com/woowahan/data/entity/dto/CartDto.kt
  data/src/main/java/com/woowahan/data/entity/table/CartTableEntity.kt
  data/src/main/java/com/woowahan/data/repository/CartRepositoryImpl.kt
  domain/src/main/java/com/woowahan/domain/model/CartListItemModel.kt
  domain/src/main/java/com/woowahan/domain/model/CartModel.kt
  domain/src/main/java/com/woowahan/domain/repository/CartRepository.kt
  domain/src/main/java/com/woowahan/domain/usecase/FetchCartItemsUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/RemoveCartItemsUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/UpdateCartItemCountUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/UpdateCartItemSelectUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/UpdateCartItemsSelectUseCase.kt
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/woowahan/banchan/CartListModelDiffUtilCallback.kt
  presentation/src/main/java/com/woowahan/banchan/bindingadapter/ImageViewBindingAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/di/UseCaseModule.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/DefaultCartAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/cart/CartActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/maindishbanchan/MainDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/root/RootActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/sidedishbanchan/SideDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/soupdishbanchan/SoupDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/CartViewModel.kt
  presentation/src/main/res/drawable/sel_checkbox.xml
  presentation/src/main/res/layout/activity_cart.xml
  presentation/src/main/res/layout/item_cart_content.xml
  presentation/src/main/res/layout/item_cart_footer.xml
  presentation/src/main/res/layout/item_cart_header.xml
  presentation/src/main/res/layout/item_empty.xml
  presentation/src/main/res/layout/item_toolbar_sub.xml
  presentation/src/main/res/values/strings.xml
Labels: Feature 📎, 영무 🍗

#94 [fix] MainDishFragment의 ItemDecorator 중첩 문제 해결
  presentation/src/main/java/com/woowahan/banchan/ui/maindishbanchan/MainDishBanchanFragment.kt
Labels: Fix 🔎, 웅재 🦊

#96 [Refactor] 반찬 클래스 리팩토링
  data/src/main/java/com/woowahan/data/entity/BanchanEntity.kt
  domain/src/main/java/com/woowahan/domain/model/BanchanModel.kt
  presentation/src/main/java/com/woowahan/banchan/bindingadapter/ImageViewBindingAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/bindingadapter/TextViewBindingAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/extension/List<BanchanModel>Extension.kt
  presentation/src/main/java/com/woowahan/banchan/ui/dialog/CartItemInsertBottomSheet.kt
  presentation/src/main/java/com/woowahan/banchan/ui/root/RootActivity.kt
  presentation/src/main/res/layout/dialog_cart_add.xml
  presentation/src/main/res/layout/item_cart_content.xml
  presentation/src/main/res/layout/item_cart_footer.xml
  presentation/src/main/res/layout/item_menu_best_horizontal_child.xml
  presentation/src/main/res/layout/item_menu_horizontal.xml
  presentation/src/main/res/layout/item_menu_vertical.xml
Labels: Refactor ⚒, 웅재 🦊, 영무 🍗, Pair 🤝

#97 [Design] 할인가가 존재한다면, 정가 text 취소선 처리
  presentation/src/main/java/com/woowahan/banchan/bindingadapter/TextViewBindingAdapter.kt
  presentation/src/main/res/layout/dialog_cart_add.xml
  presentation/src/main/res/layout/item_menu_best_horizontal_child.xml
  presentation/src/main/res/layout/item_menu_horizontal.xml
  presentation/src/main/res/layout/item_menu_vertical.xml
Labels: Design 🖍, 웅재 🦊

#89 [Test] RetrofitResponseConvertUtil Test Code 작성
  data/src/main/java/com/woowahan/data/entity/ApiServiceThrowable.kt
  data/src/main/java/com/woowahan/data/util/RetrofitResponseConvertUtil.kt
  data/src/test/java/com/resources/detail_fail.json
  data/src/test/java/com/resources/detail_success.json
  data/src/test/java/com/woowahan/data/util/RetrofitResponseConvertUtilTest.kt
Labels: Test ✍️, 웅재 🦊

#93 [Feature] 최근 본 목록 화면 구현
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/RecentlyViewedAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/recentlyviewed/RecentlyViewedActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/RecentlyViewedViewModel.kt
  presentation/src/main/res/layout/activity_recently_viewed.xml
  presentation/src/main/res/layout/item_menu_time_stamp.xml
  presentation/src/main/res/values/strings.xml
Labels: Design 🖍, Feature 📎, 웅재 🦊

#101 [Design] 최근 본 상품 목록에 취소선 적용
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/RecentViewedAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/recentviewed/RecentViewedActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/RecentViewedViewModel.kt
  presentation/src/main/res/layout/activity_recent_viewed.xml
  presentation/src/main/res/layout/item_menu_time_stamp.xml
Labels: Design 🖍, 웅재 🦊

#99 [Feature] 최근 본 목록 Room 설계
  data/src/main/java/com/woowahan/data/dao/RecentViewedDao.kt
  data/src/main/java/com/woowahan/data/database/BanchanRoomDatabase.kt
  data/src/main/java/com/woowahan/data/datasource/RecentViewedDataSource.kt
  data/src/main/java/com/woowahan/data/datasource/RecentViewedDataSourceImpl.kt
  data/src/main/java/com/woowahan/data/repository/CartRepositoryImpl.kt
  data/src/main/java/com/woowahan/data/repository/RecentViewedRepositoryImpl.kt
  domain/src/main/java/com/woowahan/domain/model/BanchanModel.kt
  domain/src/main/java/com/woowahan/domain/model/RecentViewedItemModel.kt
  domain/src/main/java/com/woowahan/domain/repository/RecentViewedRepository.kt
  domain/src/main/java/com/woowahan/domain/usecase/FetchAllRecentViewedItemUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/FetchSevenRecentViewedItemUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/InsertRecentViewedItemUseCase.kt
  domain/src/main/java/com/woowahan/domain/util/BanchanDateConvertUtil.kt
  presentation/src/main/java/com/woowahan/banchan/di/DaoModule.kt
  presentation/src/main/java/com/woowahan/banchan/di/DataSourceModule.kt
  presentation/src/main/java/com/woowahan/banchan/di/RepositoryModule.kt
  presentation/src/main/java/com/woowahan/banchan/di/UseCaseModule.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/DefaultCartAdapter.kt
Labels: Feature 📎, 영무 🍗

#104 [Feature] 기획전 화면에 장바구니 화면 연동
  presentation/src/main/java/com/woowahan/banchan/ui/bestbanchan/BestBanchanFragment.kt
Labels: Feature 📎, 웅재 🦊

#107 [Design] Cart button ripple 적용
  presentation/src/main/res/layout/item_cart_content.xml
Labels: Refactor ⚒, 영무 🍗

#109 [Refactor] Banchan, Recent Item의 Base Model 작성
  data/src/main/java/com/woowahan/data/datasource/CartDataSource.kt
  data/src/main/java/com/woowahan/data/datasource/CartDataSourceImpl.kt
  data/src/main/java/com/woowahan/data/repository/CartRepositoryImpl.kt
  data/src/main/java/com/woowahan/data/repository/RecentViewedRepositoryImpl.kt
  domain/src/main/java/com/woowahan/domain/model/BanchanModel.kt
  domain/src/main/java/com/woowahan/domain/model/BaseBanchan.kt
  domain/src/main/java/com/woowahan/domain/model/RecentViewedItemModel.kt
  domain/src/main/java/com/woowahan/domain/repository/CartRepository.kt
  domain/src/main/java/com/woowahan/domain/usecase/cart/InsertCartItemUseCase.kt
  presentation/src/main/java/com/woowahan/banchan/extension/List<BanchanModel>Extension.kt
  presentation/src/main/java/com/woowahan/banchan/extension/List<BestBanchan>Extension.kt
  presentation/src/main/java/com/woowahan/banchan/ui/dialog/CartItemInsertBottomSheet.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/BestBanchanViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/MainDishBanchanViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/RecentViewedViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SideDishBanchanViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SoupDishBanchanViewModel.kt
  presentation/src/main/res/layout/dialog_cart_add.xml
Labels: Refactor ⚒, 웅재 🦊, 영무 🍗, Pair 🤝

#113 [Feature] 최근 본 목록 View와 Room 연동
  data/src/main/java/com/woowahan/data/dao/BanchanDao.kt
  data/src/main/java/com/woowahan/data/dao/CartDao.kt
  data/src/main/java/com/woowahan/data/dao/RecentViewedDao.kt
  data/src/main/java/com/woowahan/data/database/BanchanRoomDatabase.kt
  data/src/main/java/com/woowahan/data/datasource/CartDataSourceImpl.kt
  data/src/main/java/com/woowahan/data/datasource/RecentViewedDataSourceImpl.kt
  data/src/main/java/com/woowahan/data/entity/table/RecentViewedTableEntity.kt
  domain/src/main/java/com/woowahan/domain/model/RecentViewedItemModel.kt
  presentation/src/main/java/com/woowahan/banchan/RecentViewedModelDiffUtilCallback.kt
  presentation/src/main/java/com/woowahan/banchan/bindingadapter/TextViewBindingAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/di/DaoModule.kt
  presentation/src/main/java/com/woowahan/banchan/extension/DateExtension.kt
  presentation/src/main/java/com/woowahan/banchan/extension/List<RecentViewedItemModel>Extension.kt
  presentation/src/main/java/com/woowahan/banchan/extension/List<RecentViewedModel>Extension.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/RecentViewedAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/bestbanchan/BestBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/recentviewed/RecentViewedActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/BestBanchanViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/RecentViewedViewModel.kt
  presentation/src/main/res/layout/item_menu_time_stamp.xml
Labels: Feature 📎, 영무 🍗

#116 [Fix] Cart Payload 수정
  domain/src/main/java/com/woowahan/domain/model/CartListItemModel.kt
  presentation/src/main/java/com/woowahan/banchan/CartListModelDiffUtilCallback.kt
Labels: Fix 🔎, 웅재 🦊

#118 [Refactor] 도메인, 데이터모듈 에러 처리 방식 수정
  data/src/main/java/com/woowahan/data/dao/CartDao.kt
  data/src/main/java/com/woowahan/data/datasource/BanchanDetailDataSource.kt
  data/src/main/java/com/woowahan/data/datasource/BanchanDetailRetrofitDataSourceImpl.kt
  data/src/main/java/com/woowahan/data/datasource/BanchansDataSource.kt
  data/src/main/java/com/woowahan/data/datasource/BanchansRetrofitDataSourceImpl.kt
  data/src/main/java/com/woowahan/data/datasource/CartDataSource.kt
  data/src/main/java/com/woowahan/data/datasource/CartDataSourceImpl.kt
  data/src/main/java/com/woowahan/data/datasource/RecentViewedDataSourceImpl.kt
  data/src/main/java/com/woowahan/data/repository/BanchanDetailRepositoryImpl.kt
  data/src/main/java/com/woowahan/data/repository/BanchanRepositoryImpl.kt
  data/src/main/java/com/woowahan/data/repository/CartRepositoryImpl.kt
  data/src/main/java/com/woowahan/data/repository/RecentViewedRepositoryImpl.kt
  data/src/main/java/com/woowahan/data/util/RetrofitResponseConvertUtil.kt
  data/src/test/java/com/woowahan/data/util/RetrofitResponseConvertUtilTest.kt
  domain/src/main/java/com/woowahan/domain/model/ApiServiceThrowable.kt
  domain/src/main/java/com/woowahan/domain/model/DomainEvent.kt
  domain/src/main/java/com/woowahan/domain/repository/BanchanDetailRepository.kt
  domain/src/main/java/com/woowahan/domain/repository/BanchanRepository.kt
  domain/src/main/java/com/woowahan/domain/repository/CartRepository.kt
  domain/src/main/java/com/woowahan/domain/repository/RecentViewedRepository.kt
  domain/src/main/java/com/woowahan/domain/usecase/banchan/FetchBestBanchanUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/banchan/FetchMainDishBanchanUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/banchan/FetchSideDishBanchanUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/banchan/FetchSoupDishBanchanUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/cart/FetchCartItemsKeyUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/cart/FetchCartItemsUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/cart/GetCartItemsSizeFlowUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/cart/InsertCartItemUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/cart/RemoveCartItemUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/cart/UpdateCartItemCountUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/cart/UpdateCartItemSelectUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/recentviewed/FetchRecentViewedItemUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/recentviewed/InsertRecentViewedItemUseCase.kt
  presentation/src/main/java/com/woowahan/banchan/di/RepositoryModule.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/BestBanchanViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/CartViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/MainDishBanchanViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/RecentViewedViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/RootViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SideDishBanchanViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SoupDishBanchanViewModel.kt
Labels: Refactor ⚒, 웅재 🦊

#119 [Feature] 주문하기 기능 Data, Domain 모듈 작성
  data/src/main/java/com/woowahan/data/dao/OrderDao.kt
  data/src/main/java/com/woowahan/data/database/BanchanRoomDatabase.kt
  data/src/main/java/com/woowahan/data/datasource/OrderDataSource.kt
  data/src/main/java/com/woowahan/data/datasource/OrderDataSourceImpl.kt
  data/src/main/java/com/woowahan/data/entity/dto/OrderDto.kt
  data/src/main/java/com/woowahan/data/entity/table/OrderItemTableEntity.kt
  data/src/main/java/com/woowahan/data/entity/table/OrderTableEntity.kt
  data/src/main/java/com/woowahan/data/repository/OrderRepositoryImpl.kt
  domain/src/main/java/com/woowahan/domain/model/OrderModel.kt
  domain/src/main/java/com/woowahan/domain/repository/OrderRepository.kt
  domain/src/main/java/com/woowahan/domain/usecase/order/FetchOrderUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/order/FetchOrdersUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/order/GetDeliveryOrderCountUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/order/InsertOrderUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/order/UpdateOrderUseCase.kt
  presentation/src/main/java/com/woowahan/banchan/di/DaoModule.kt
  presentation/src/main/java/com/woowahan/banchan/di/DataSourceModule.kt
  presentation/src/main/java/com/woowahan/banchan/di/RepositoryModule.kt
  presentation/src/main/java/com/woowahan/banchan/di/UseCaseModule.kt
  presentation/src/main/java/com/woowahan/banchan/ui/cart/CartActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/root/RootActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/CartViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/RootViewModel.kt
Labels: Feature 📎, 웅재 🦊

#124 [Fix] Cart Payload 수정
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/DefaultCartAdapter.kt
Labels: Fix 🔎, 영무 🍗

#114 [Feature] Cart payload 구현
  domain/src/main/java/com/woowahan/domain/model/CartListItemModel.kt
  presentation/src/main/java/com/woowahan/banchan/CartListModelDiffUtilCallback.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/DefaultCartAdapter.kt
  presentation/src/main/res/layout/item_cart_content.xml
  presentation/src/main/res/layout/item_cart_footer.xml
Labels: Feature 📎, 영무 🍗

#128 [Feature] 주문하기 Presentation 모듈 작성
  data/src/main/java/com/woowahan/data/dao/OrderDao.kt
  domain/src/main/java/com/woowahan/domain/model/OrderModel.kt
  domain/src/main/java/com/woowahan/domain/usecase/order/FetchOrderUseCase.kt
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/woowahan/banchan/ui/cart/CartActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/order/OrderItemActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/order/OrderItemAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/order/OrderListActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/order/OrderListAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/root/RootActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/CartViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/OrderItemViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/OrderListViewModel.kt
  presentation/src/main/res/drawable/ic_arrow_right_black.xml
  presentation/src/main/res/drawable/ic_refresh.xml
  presentation/src/main/res/layout/activity_order_item.xml
  presentation/src/main/res/layout/activity_order_list.xml
  presentation/src/main/res/layout/item_order_horizontal.xml
  presentation/src/main/res/layout/item_order_list.xml
  presentation/src/main/res/layout/item_order_state_footer.xml
  presentation/src/main/res/layout/item_order_state_header.xml
  presentation/src/main/res/menu/menu_order_item.xml
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/strings.xml
Labels: Feature 📎, 웅재 🦊

#130 [Fix] 장바구니 footer 버튼 감추는 조건 수정
  domain/src/main/java/com/woowahan/domain/model/CartListItemModel.kt
  domain/src/main/java/com/woowahan/domain/usecase/cart/FetchCartItemsUseCase.kt
  presentation/src/main/java/com/woowahan/banchan/extension/DateExtension.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/DefaultCartAdapter.kt
  presentation/src/main/res/layout/item_cart_footer.xml
Labels: Fix 🔎, 영무 🍗

#126 [Feature] 장바구니 세부사항 구현
  data/src/main/java/com/woowahan/data/repository/RecentViewedRepositoryImpl.kt
  domain/src/main/java/com/woowahan/domain/model/CartListItemModel.kt
  domain/src/main/java/com/woowahan/domain/model/RecentViewedItemModel.kt
  domain/src/main/java/com/woowahan/domain/usecase/cart/FetchCartItemsUseCase.kt
  presentation/src/main/java/com/woowahan/banchan/CartListModelDiffUtilCallback.kt
  presentation/src/main/java/com/woowahan/banchan/bindingadapter/EditTextBindingAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/di/UseCaseModule.kt
  presentation/src/main/java/com/woowahan/banchan/extension/DateExtension.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/DefaultCartAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/HorizontalBanchanListAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/RecentViewedHorizontalAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/cart/CartActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/BestBanchanViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/CartViewModel.kt
  presentation/src/main/res/layout/item_cart_content.xml
  presentation/src/main/res/layout/item_cart_empty.xml
  presentation/src/main/res/layout/item_cart_footer.xml
  presentation/src/main/res/layout/item_cart_header.xml
  presentation/src/main/res/layout/item_menu_small.xml
  presentation/src/main/res/values/strings.xml
Labels: Feature 📎, 영무 🍗

#136 [Refactor] Delivery constant 적용
  data/src/main/java/com/woowahan/data/entity/BanchanDetailEntity.kt
  data/src/main/java/com/woowahan/data/repository/BanchanDetailRepositoryImpl.kt
  domain/src/main/java/com/woowahan/domain/constant/DeliveryConstant.kt
  domain/src/main/java/com/woowahan/domain/model/BanchanDetailModel.kt
  domain/src/main/java/com/woowahan/domain/model/CartListItemModel.kt
  domain/src/main/java/com/woowahan/domain/model/OrderModel.kt
  domain/src/main/java/com/woowahan/domain/usecase/cart/FetchCartItemsUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/order/FetchOrderUseCase.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/DefaultCartAdapter.kt
Labels: Refactor ⚒, 웅재 🦊

#139 [Refactor] banchan view model 추상화 하여 재사용성 올리기
  domain/src/main/java/com/woowahan/domain/usecase/recentviewed/FetchRecentViewedItemUseCase.kt
  presentation/src/main/java/com/woowahan/banchan/di/UseCaseModule.kt
  presentation/src/main/java/com/woowahan/banchan/extension/List<BanchanModel>Extension.kt
  presentation/src/main/java/com/woowahan/banchan/extension/List<BestBanchan>Extension.kt
  presentation/src/main/java/com/woowahan/banchan/extension/List<RecentViewedItemModel>Extension.kt
  presentation/src/main/java/com/woowahan/banchan/extension/List<RecentViewedModel>Extension.kt
  presentation/src/main/java/com/woowahan/banchan/ui/base/BaseActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/base/BaseFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/recentviewed/RecentViewedActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/BaseCartUpdateViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/BestBanchanViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/MainDishBanchanViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/RecentViewedViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SideDishBanchanViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SoupDishBanchanViewModel.kt
Labels: Refactor ⚒, 웅재 🦊

#135 [Fix] Order Item 화면에서, Footer에 가격 적용 안되고 있는 문제 수정
  domain/src/main/java/com/woowahan/domain/model/OrderModel.kt
  domain/src/main/java/com/woowahan/domain/usecase/order/FetchOrderUseCase.kt
  presentation/src/main/java/com/woowahan/banchan/ui/order/OrderItemAdapter.kt
Labels: Fix 🔎, 웅재 🦊

#141 [Design] Banchan Detail UI 작업
  domain/src/main/java/com/woowahan/domain/model/BanchanDetailModel.kt
  domain/src/main/java/com/woowahan/domain/usecase/banchan/FetchBanchanDetailUseCase.kt
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/woowahan/banchan/di/UseCaseModule.kt
  presentation/src/main/java/com/woowahan/banchan/ui/bestbanchan/BestBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/detail/BanchanDetailActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/DetailViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/RecentViewedViewModel.kt
  presentation/src/main/res/layout/activity_banchan_detail.xml
  presentation/src/main/res/values/strings.xml
Labels: Design 🖍, 영무 🍗

#149 [Feature] Splash 화면 추가
  domain/src/main/java/com/woowahan/domain/model/BanchanDetailModel.kt
  presentation/build.gradle
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/ic_launcher-playstore.png
  presentation/src/main/java/com/woowahan/banchan/ui/root/RootActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/RootViewModel.kt
  presentation/src/main/res/drawable-v24/ic_launcher_foreground.xml
  presentation/src/main/res/drawable/ic_launcher_foreground.xml
  presentation/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  presentation/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  presentation/src/main/res/mipmap-hdpi/ic_launcher.png
  presentation/src/main/res/mipmap-hdpi/ic_launcher.webp
  presentation/src/main/res/mipmap-hdpi/ic_launcher_round.png
  presentation/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  presentation/src/main/res/mipmap-mdpi/ic_launcher.png
  presentation/src/main/res/mipmap-mdpi/ic_launcher.webp
  presentation/src/main/res/mipmap-mdpi/ic_launcher_round.png
  presentation/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  presentation/src/main/res/mipmap-xhdpi/ic_launcher.png
  presentation/src/main/res/mipmap-xhdpi/ic_launcher.webp
  presentation/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  presentation/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  presentation/src/main/res/mipmap-xxhdpi/ic_launcher.png
  presentation/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  presentation/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  presentation/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  presentation/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  presentation/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  presentation/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  presentation/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  presentation/src/main/res/values/ic_launcher_background.xml
  presentation/src/main/res/values/themes.xml
Labels: Feature 📎, 웅재 🦊, 영무 🍗, Pair 🤝

#148 [Fix] CartItem 제거시 Exception 발생 수정
  data/src/main/java/com/woowahan/data/datasource/CartDataSourceImpl.kt
Labels: Fix 🔎, 웅재 🦊

#150 [Fix] OrderList에서 가격정보가 단일 Item 가격만 표시되는 문제 수정
  data/src/main/java/com/woowahan/data/repository/OrderRepositoryImpl.kt
  domain/src/main/java/com/woowahan/domain/model/OrderModel.kt
  domain/src/main/java/com/woowahan/domain/usecase/order/FetchOrderUseCase.kt
  presentation/src/main/java/com/woowahan/banchan/ui/order/OrderListAdapter.kt
  presentation/src/main/res/layout/item_order_list.xml
Labels: Feature 📎, 웅재 🦊

#153 [Feature] 네트워크 상태 처리
  domain/src/main/java/com/woowahan/domain/model/ApiServiceThrowable.kt
  presentation/src/main/java/com/woowahan/banchan/di/RetrofitModule.kt
  presentation/src/main/java/com/woowahan/banchan/extension/AppCompatExtension.kt
  presentation/src/main/java/com/woowahan/banchan/network/NetworkConnectionInterceptor.kt
  presentation/src/main/java/com/woowahan/banchan/ui/base/BaseNetworkActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/cart/CartActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/detail/BanchanDetailActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/recentviewed/RecentViewedActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/root/RootActivity.kt
  presentation/src/main/res/layout/activity_main.xml
  presentation/src/main/res/values/strings.xml
Labels: Feature 📎, 웅재 🦊

#154 [Fix] ViewModel Flow 수정
  presentation/src/main/java/com/woowahan/banchan/background/DeliveryRequester.kt
  presentation/src/main/java/com/woowahan/banchan/ui/bestbanchan/BestBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/cart/CartActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/maindishbanchan/MainDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/order/OrderItemActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/order/OrderListActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/recentviewed/RecentViewedActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/sidedishbanchan/SideDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/soupdishbanchan/SoupDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/BestBanchanViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/CartViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/MainDishBanchanViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/OrderItemViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/OrderListViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/RecentViewedViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SideDishBanchanViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SoupDishBanchanViewModel.kt
  presentation/src/main/res/layout/activity_cart.xml
  presentation/src/main/res/layout/activity_order_list.xml
  presentation/src/main/res/layout/activity_recent_viewed.xml
  presentation/src/main/res/layout/fragment_best_banchan.xml
  presentation/src/main/res/layout/fragment_main_dish_banchan.xml
  presentation/src/main/res/layout/fragment_side_dish_banchan.xml
  presentation/src/main/res/layout/fragment_soup_dish_banchan.xml
Labels: Fix 🔎, 웅재 🦊

#156 [Test] Banchan DataSource 테스트 코드 수정
  data/src/test/java/com/woowahan/data/datasource/BanchansRetrofitDataSourceImplTest.kt
Labels: Test ✍️, 웅재 🦊

#155 [Test] Cart Data 모듈 테스트 코드 작성
  data/build.gradle
  data/src/androidTest/java/com/woowahan/data/ExampleInstrumentedTest.kt
  data/src/androidTest/java/com/woowahan/data/dao/CartDaoTest.kt
  data/src/test/java/com/resources/banchan_detail_success.json
  data/src/test/java/com/woowahan/data/dao/SpyBanchanDaoImpl.kt
  data/src/test/java/com/woowahan/data/dao/SpyCartDaoImpl.kt
  data/src/test/java/com/woowahan/data/datasource/CartDataSourceImplTest.kt
  data/src/test/java/com/woowahan/data/datasource/SpyBanchanDetailDataSourceImpl.kt
  data/src/test/java/com/woowahan/data/datasource/SpyCartDataSourceImpl.kt
  data/src/test/java/com/woowahan/data/repository/CartRepositoryImplTest.kt
Labels: Test ✍️, 웅재 🦊

#159 [Fix] 화면 진입시마다 네트워크 안내가 표시되는 문제 수정
  presentation/src/main/java/com/woowahan/banchan/ui/base/BaseNetworkActivity.kt
  presentation/src/main/res/layout/activity_cart.xml
Labels: Fix 🔎, 웅재 🦊

#160 [Feature] Banchan Detail 화면 연동
  data/src/main/java/com/woowahan/data/datasource/RecentViewedDataSource.kt
  data/src/main/java/com/woowahan/data/datasource/RecentViewedDataSourceImpl.kt
  data/src/main/java/com/woowahan/data/entity/BanchanDetailEntity.kt
  data/src/main/java/com/woowahan/data/entity/dto/RecentViewedDto.kt
  data/src/main/java/com/woowahan/data/entity/table/RecentViewedTableEntity.kt
  data/src/main/java/com/woowahan/data/repository/BanchanDetailRepositoryImpl.kt
  data/src/main/java/com/woowahan/data/repository/CartRepositoryImpl.kt
  data/src/main/java/com/woowahan/data/repository/RecentViewedRepositoryImpl.kt
  domain/src/main/java/com/woowahan/domain/model/BanchanDetailModel.kt
  domain/src/main/java/com/woowahan/domain/model/CartListItemModel.kt
  domain/src/main/java/com/woowahan/domain/repository/CartRepository.kt
  domain/src/main/java/com/woowahan/domain/repository/RecentViewedRepository.kt
  domain/src/main/java/com/woowahan/domain/usecase/banchan/FetchBanchanDetailUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/cart/InsertCartItemUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/recentviewed/FetchRecentViewedItemUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/recentviewed/InsertRecentViewedItemUseCase.kt
  presentation/src/main/java/com/woowahan/banchan/di/UseCaseModule.kt
  presentation/src/main/java/com/woowahan/banchan/extension/AppCompatExtension.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/DefaultBanchanAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/DefaultCartAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/ImageAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/RecentViewedAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/RecentViewedHorizontalAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/ViewModeToggleBanchanAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/viewHolder/MenuHorizontalViewHolder.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/viewHolder/MenuVerticalViewHolder.kt
  presentation/src/main/java/com/woowahan/banchan/ui/cart/CartActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/detail/BanchanDetailActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/maindishbanchan/MainDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/recentviewed/RecentViewedActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/sidedishbanchan/SideDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/soupdishbanchan/SoupDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/BaseCartUpdateViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/BestBanchanViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/CartViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/DetailViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/MainDishBanchanViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/RecentViewedViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SideDishBanchanViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SoupDishBanchanViewModel.kt
  presentation/src/main/res/drawable/bg_indicator_select.xml
  presentation/src/main/res/drawable/bg_indicator_unselect.xml
  presentation/src/main/res/drawable/ic_indicator_select.xml
  presentation/src/main/res/drawable/ic_indicator_unselect.xml
  presentation/src/main/res/drawable/sel_indicator.xml
  presentation/src/main/res/layout/activity_banchan_detail.xml
  presentation/src/main/res/layout/item_menu_detail_image.xml
  presentation/src/main/res/layout/item_menu_horizontal.xml
  presentation/src/main/res/layout/item_menu_small.xml
  presentation/src/main/res/layout/item_menu_thumb_image.xml
  presentation/src/main/res/layout/item_menu_time_stamp.xml
  presentation/src/main/res/layout/item_menu_vertical.xml
  presentation/src/main/res/values/strings.xml
Labels: Feature 📎, 영무 🍗

#167 [Fix] RecentViewed Item의 Hash가 같은데, Replace되지 않고 Insert되는 문제 수정
  data/src/main/java/com/woowahan/data/entity/table/RecentViewedTableEntity.kt
Labels: Fix 🔎, 웅재 🦊

#168 [Feature] Banchan Detail Cache DataSource 생성, 적용
  data/src/main/java/com/woowahan/data/datasource/BanchanDetailCacheDataSource.kt
  data/src/main/java/com/woowahan/data/datasource/BanchanDetailCacheDataSourceImpl.kt
  data/src/main/java/com/woowahan/data/repository/CartRepositoryImpl.kt
  data/src/main/java/com/woowahan/data/repository/RecentViewedRepositoryImpl.kt
  presentation/src/main/java/com/woowahan/banchan/di/DataSourceModule.kt
  presentation/src/main/java/com/woowahan/banchan/di/RepositoryModule.kt
Labels: Feature 📎, 웅재 🦊

#164 [Feature] 페이징 적용
  data/build.gradle
  data/src/androidTest/java/com/woowahan/data/dao/CartDaoTest.kt
  data/src/main/java/com/woowahan/data/dao/OrderDao.kt
  data/src/main/java/com/woowahan/data/dao/RecentViewedDao.kt
  data/src/main/java/com/woowahan/data/datasource/OrderDataSource.kt
  data/src/main/java/com/woowahan/data/datasource/OrderDataSourceImpl.kt
  data/src/main/java/com/woowahan/data/datasource/RecentViewedDataSource.kt
  data/src/main/java/com/woowahan/data/datasource/RecentViewedDataSourceImpl.kt
  data/src/main/java/com/woowahan/data/entity/dto/OrderDto.kt
  data/src/main/java/com/woowahan/data/entity/dto/RecentViewedDto.kt
  data/src/main/java/com/woowahan/data/entity/table/OrderTableEntity.kt
  data/src/main/java/com/woowahan/data/entity/table/RecentViewedTableEntity.kt
  data/src/main/java/com/woowahan/data/repository/OrderRepositoryImpl.kt
  data/src/main/java/com/woowahan/data/repository/RecentViewedRepositoryImpl.kt
  domain/build.gradle
  domain/src/main/java/com/woowahan/domain/model/RecentViewedItemModel.kt
  domain/src/main/java/com/woowahan/domain/repository/OrderRepository.kt
  domain/src/main/java/com/woowahan/domain/repository/RecentViewedRepository.kt
  domain/src/main/java/com/woowahan/domain/usecase/order/FetchOrderPagingUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/recentviewed/FetchRecentViewedPagingUseCase.kt
  presentation/build.gradle
  presentation/src/main/java/com/woowahan/banchan/di/UseCaseModule.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/RecentViewedAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/order/OrderListActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/order/OrderListAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/order/OrderListItemViewHolder.kt
  presentation/src/main/java/com/woowahan/banchan/ui/order/OrderListPagingAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/recentviewed/RecentViewedActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/DetailViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/OrderListViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/RecentViewedViewModel.kt
  presentation/src/main/res/layout/activity_order_list.xml
  presentation/src/main/res/layout/item_order_list.xml
Labels: Feature 📎, 웅재 🦊, 영무 🍗, Pair 🤝

#163 [Feature] Base Error View Model 추가 후 에러처리가 필요한 ViewModel이 구현하도록 설정
  data/src/main/java/com/woowahan/data/repository/RecentViewedRepositoryImpl.kt
  data/src/test/java/com/woowahan/data/dao/SpyRecentViewedDaoImpl.kt
  domain/src/main/java/com/woowahan/domain/usecase/cart/FetchCartItemsUseCase.kt
  presentation/src/main/java/com/woowahan/banchan/ui/bestbanchan/BestBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/maindishbanchan/MainDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/order/OrderListActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/recentviewed/RecentViewedActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/sidedishbanchan/SideDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/soupdishbanchan/SoupDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/BaseCartUpdateViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/BaseErrorViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/BestBanchanViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/MainDishBanchanViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/OrderListViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/RecentViewedViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SideDishBanchanViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SoupDishBanchanViewModel.kt
  presentation/src/main/res/drawable/ic_retry.xml
  presentation/src/main/res/layout/activity_order_list.xml
  presentation/src/main/res/layout/activity_recent_viewed.xml
  presentation/src/main/res/layout/fragment_best_banchan.xml
  presentation/src/main/res/layout/fragment_main_dish_banchan.xml
  presentation/src/main/res/layout/fragment_side_dish_banchan.xml
  presentation/src/main/res/layout/fragment_soup_dish_banchan.xml
  presentation/src/main/res/layout/item_cart_footer.xml
  presentation/src/main/res/layout/item_error_button_view.xml
Labels: Feature 📎, 웅재 🦊, 영무 🍗, Pair 🤝

#171 [Feature] Firebase Crashlytics 플러그인 추가
  build.gradle
  presentation/build.gradle
Labels: Feature 📎, 웅재 🦊, 영무 🍗, Pair 🤝

#173 [Fix] 장바구니 삭제 후 최근 본 목록화면에서 재등록 시 주문하기 안보임
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/DefaultCartAdapter.kt
Labels: Fix 🔎, 영무 🍗

#176 [Fix] 장바구니 수량 조절 안 먹히는 버그 수정
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/DefaultCartAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/CartViewModel.kt
  presentation/src/main/res/layout/item_cart_content.xml
Labels: Fix 🔎, 영무 🍗

#178 [Fix] payload 여러개 처리 에러
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/DefaultCartAdapter.kt
Labels: Fix 🔎, 영무 🍗

#180 [Bug] 밑반찬, 국물요리 총 아이템 수 버그
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/DefaultBanchanAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/viewHolder/CountHeaderViewHolder.kt
Labels: 영무 🍗, Bug 🙀

#200 [Feature] Banchan Detail 화면에서 에러 발생시 처리
  presentation/src/main/java/com/woowahan/banchan/ui/detail/BanchanDetailActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/DetailViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/util/DialogUtil.kt
Labels: Feature 📎, 웅재 🦊

#201 [Release] 1.0.1 배포 준비
  .gitignore
  presentation/build.gradle
  presentation/src/main/java/com/woowahan/banchan/background/DeliveryRequester.kt
Labels: 웅재 🦊, 영무 🍗, Pair 🤝, Release 📱

#204 [Bug] 장바구니에서 수량 0개로 입력한 상황 핸들링 필요
  presentation/release/output-metadata.json
  presentation/src/main/java/com/woowahan/banchan/bindingadapter/EditTextBindingAdapter.kt
Labels: 영무 🍗, Bug 🙀

#210 [Bug] "선택한 상품이 장바구니에 담겼습니다" dialog가 뜬 상태에서 화면 회전하면 dialog 없어짐
  presentation/src/main/java/com/woowahan/banchan/ui/bestbanchan/BestBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/detail/BanchanDetailActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/dialog/MainDialog.kt
  presentation/src/main/java/com/woowahan/banchan/ui/dialog/MainDialogFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/maindishbanchan/MainDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/recentviewed/RecentViewedActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/sidedishbanchan/SideDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/soupdishbanchan/SoupDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/MainDialogViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/util/DialogUtil.kt
  presentation/src/main/res/layout/dialog_main.xml
Labels: 웅재 🦊, Bug 🙀

#212 [Bug] 디바이스 재부팅시 주문 상태가 업데이트 되지 않음
  data/src/main/java/com/woowahan/data/dao/OrderDao.kt
  data/src/main/java/com/woowahan/data/datasource/OrderDataSource.kt
  data/src/main/java/com/woowahan/data/datasource/OrderDataSourceImpl.kt
  data/src/main/java/com/woowahan/data/repository/OrderRepositoryImpl.kt
  domain/src/main/java/com/woowahan/domain/repository/OrderRepository.kt
  domain/src/main/java/com/woowahan/domain/usecase/order/UpdateMissingDeliveryOrderUseCase.kt
  domain/src/main/java/com/woowahan/domain/usecase/order/UpdateOrderUseCase.kt
  presentation/src/main/java/com/woowahan/banchan/background/DeliveryAlarmReceiver.kt
  presentation/src/main/java/com/woowahan/banchan/background/DeliveryWorker.kt
  presentation/src/main/java/com/woowahan/banchan/di/UseCaseModule.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/RootViewModel.kt
Labels: Feature 📎, 웅재 🦊, Bug 🙀

#211 [Bug] 메인화면 탭 Spinner Filter 버그 수정
  domain/src/main/java/com/woowahan/domain/model/BanchanModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/DefaultBanchanAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/sidedishbanchan/SideDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/soupdishbanchan/SoupDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/BaseCartUpdateViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/MainDishBanchanViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SideDishBanchanViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SoupDishBanchanViewModel.kt
Labels: 웅재 🦊, Bug 🙀

#206 [Feature] Presentation 에러 처리 변경
  data/src/main/java/com/woowahan/data/dao/RecentViewedDao.kt
  data/src/main/java/com/woowahan/data/datasource/RecentViewedDataSource.kt
  data/src/main/java/com/woowahan/data/datasource/RecentViewedDataSourceImpl.kt
  data/src/main/java/com/woowahan/data/repository/CartRepositoryImpl.kt
  data/src/main/java/com/woowahan/data/repository/RecentViewedRepositoryImpl.kt
  domain/src/main/java/com/woowahan/domain/model/ApiServiceThrowable.kt
  domain/src/main/java/com/woowahan/domain/repository/RecentViewedRepository.kt
  domain/src/main/java/com/woowahan/domain/usecase/recentviewed/FetchRecentViewedPagingUseCase.kt
  presentation/src/main/java/com/woowahan/banchan/di/UseCaseModule.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/RecentViewedAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/base/BaseNetworkActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/cart/CartActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/recentviewed/RecentViewedActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/BaseErrorViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/BestBanchanViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/CartViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/MainDishBanchanViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/OrderListViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/RecentViewedViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SideDishBanchanViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/SoupDishBanchanViewModel.kt
  presentation/src/main/res/layout/activity_cart.xml
  presentation/src/main/res/layout/fragment_best_banchan.xml
  presentation/src/main/res/layout/fragment_main_dish_banchan.xml
  presentation/src/main/res/layout/fragment_side_dish_banchan.xml
  presentation/src/main/res/layout/fragment_soup_dish_banchan.xml
Labels: Feature 📎, 웅재 🦊

#207 [Bug] OrderList, Order화면 수정
  presentation/src/main/java/com/woowahan/banchan/background/DeliveryRequester.kt
  presentation/src/main/java/com/woowahan/banchan/ui/order/OrderItemAdapter.kt
  presentation/src/main/res/layout/item_order_list.xml
Labels: 웅재 🦊, Bug 🙀

#208 [Bug] 빠르게 장바구니 아이콘 클릭시 바텀 시트 여러개 뜸
  presentation/src/main/java/com/woowahan/banchan/ui/bestbanchan/BestBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/dialog/CartItemInsertBottomSheet.kt
  presentation/src/main/java/com/woowahan/banchan/ui/maindishbanchan/MainDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/recentviewed/RecentViewedActivity.kt
  presentation/src/main/java/com/woowahan/banchan/ui/sidedishbanchan/SideDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/soupdishbanchan/SoupDishBanchanFragment.kt
Labels: 웅재 🦊, Bug 🙀

#214 [Bug] 장바구니에서 화면 회전시 crash
  presentation/src/main/AndroidManifest.xml
Labels: 영무 🍗, Bug 🙀

#215 [Bug] Editext 999에서 버튼 클릭시 100
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/CartViewModel.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/DetailViewModel.kt
  presentation/src/main/res/layout/item_cart_content.xml
Labels: 영무 🍗, Bug 🙀

#216 [Release] 1.0.2
  presentation/build.gradle
Labels: 웅재 🦊, 영무 🍗, Pair 🤝, Release 📱

#217 [Bug] 장바구니에서 화면 회전시 crash
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/BestBanchanAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/DefaultBanchanAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/DefaultCartAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/RecentViewedAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/adapter/ViewModeToggleBanchanAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/maindishbanchan/MainDishBanchanFragment.kt
  presentation/src/main/java/com/woowahan/banchan/ui/order/OrderItemAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/order/OrderListAdapter.kt
  presentation/src/main/java/com/woowahan/banchan/ui/viewmodel/MainDishBanchanViewModel.kt
Labels: 웅재 🦊, 영무 🍗, Bug 🙀

#219 [Release] 1.0.3
  presentation/build.gradle
Labels: 웅재 🦊, 영무 🍗, Pair 🤝, Release 📱
